# Generated by Django 4.1.5 on 2023-01-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalApp', '0002_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='gender',
            field=models.CharField(choices=[('Female', 'F'), ('Male', 'M')], max_length=50),
        ),
    ]
